.Language=English,English

plugin.name = <(NAME)>

# Password dialog
password.title = Enter password
password.password = Password:

# Generic buttons
button.ok = OK
button.cancel = Cancel

# Size and speed suffixes
suffix.size.b = B
suffix.size.kb = KB
suffix.size.mb = MB
suffix.size.gb = GB
suffix.size.tb = TB
suffix.speed.b = B/s
suffix.speed.kb = KB/s
suffix.speed.mb = MB/s
suffix.speed.gb = GB/s
suffix.speed.tb = TB/s
