.Language=English,English

plugin.name = MsiUpdate

# Configuration dialog
config.title = Настройки
config.use_full_install_ui = &Ручная установка
config.update_stable_builds = Обновлять &стабильные сборки
config.logged_install = Запись &лога при установке
config.install_properties = &Дополнительные параметры:
config.use_proxy = Использовать собственные настройки &прокси
config.proxy_server = &Имя сервера:
config.proxy_port = П&орт:
config.proxy_auth_scheme = С&хема авторизации:
config.proxy_auth.basic = Basic
config.proxy_auth.ntlm = NTLM
config.proxy_auth.passport = Passport
config.proxy_auth.digest = Digest
config.proxy_auth.negotiate = Negotiate
config.proxy_user_name = И&мя пользователя:
config.proxy_password = П&ароль:
config.cache_enabled = Сохра&нять инсталляционные пакеты локально
config.cache_max_size = Макс. &число пакетов:
config.cache_dir = &Каталог для сохранения:

# Update dialog
update.new_version = Доступна новая версия: 
update.no_new_version = У вас установлена последняя версия.
update.question = Хотите запустить обновление?
update.changelog = &Посмотреть изменения

# Download progress
download.title = Загрузка
download.message = Загрузка данных

# Generic buttons
button.ok = OK
button.cancel = Отмена
button.yes = Да
button.no = Нет

# Errors
error.no_msi = MSI пакет не установлен.
error.editor_unsaved = Открыто окно редактора с несохраненными данными.
