.Language=English,English

plugin.name = MsiUpdate

# Configuration dialog
config.title = Настройки
config.use_full_install_ui = &Ручная установка
config.update_stable_builds = Обновлять &стабильные сборки
config.logged_install = Запись &лога при установке

# Update dialog
update.new_version = Доступна новая версия: 
update.no_new_version = У вас установлена последняя версия.
update.question = Хотите запустить обновление?

# Generic buttons
button.ok = OK
button.cancel = Отмена

# Errors
error.no_msi = MSI пакет не установлен.
